### ISSUE TITLE
Refactor `Enrgy_sub`, move all `Enrgy_` functions

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/STEMMUS_SCOPE#100]
In STEMMUS_SCOPE.m, all `Enrgy_` functions are called using the script `Enrgy_sub`:

https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/d2fe0a671ab26430f086e1c8ee8272f4db6fa060/src/STEMMUS_SCOPE.m#L751

However, for model maintainability we want to remove all use of globals and running scripts.

Additionally, as all `Enrgy_` functions seem to tackle one specific part of the model, these should be moved to a separate Matlab package with a appropriate name.

<hr>

To do:
- [ ] Move all `Enrgy_` files to their own package, with an appropriate name
- [ ] Convert `Enrgy_sub` into a function. Use structures to reduce the amount of input and output variables.
- [ ] Add documentation to all functions
- [ ] Make the required changes in the main file.
- [ ] Create a pull request for the changes

**Comment by SarahAlidoost** [comment]
@yijianzeng For each function below, please add one line explanation and suggest a better name in this issue, thanks

- Enrgy_sub
- EnrgyPARM
- Enrgy_MAT
- Enrgy_EQ
- Enrgy_BC
- Enrgy_Solve
- Enrgy_Bndry_Flux

**Comment by SarahAlidoost** [comment]
@yijianzeng please help to answer the question above. thanks

**Comment by yijianzeng** [comment]
> * Enrgy_sub

This function is to solve the Energy balance equation with the Thomas algorithm ('Air_solve') to update the soil temperature ('TT'), the finite difference time-stepping scheme is exampled as for the soil moisture equation, which is derived in 'STEMMUS Technical Notes' section 4, Equation 4.32.

**Comment by yijianzeng** [comment]
> * EnrgyPARM

This function calculates all the parameters related to energy balance equation (e.g., Equation 3.65-3.73, STEMMUS Technical Notes, page 29-32).

**Comment by yijianzeng** [comment]
> * Enrgy_MAT

This function calculates all the parameters related to matric coefficients (e.g., c1-c7) as in Equation 4.32 (STEMMUS Technical Notes, page 44, which is an example for soil moisture equation), but here it is for energy equation.

**Comment by yijianzeng** [comment]
> * Enrgy_EQ

This function assembles the coefficient matrices of Equation 4.32 (STEMMUS Technical Notes, page 44, the example was only shown for the soil moisture equation), but here it is for the energy equation.

**Comment by yijianzeng** [comment]
> * Enrgy_BC

This function determines the boundary condition for solving the energy equation.

**Comment by yijianzeng** [comment]
> * Enrgy_Solve

This function uses Thomas algorithm to solve the tridiagonal matrix equations, which is in the form of Equation 4.25 (STEMMUS Technical Notes, page 41)

**Comment by yijianzeng** [comment]
> * Enrgy_Bndry_Flux

This function calculates the energy fluxes on the boundary nodes.

**Comment by SarahAlidoost** [comment]
While refactoring `Enrgy_sub` functions, I found two issues:
1. The variables calculated in [these lines](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/938cc963c7754f56ccc30bb1e3b5764542d08d64/src/EnrgyPARM.m#L42-L45) are unused in the model.
2. The function [Enrgy_Bndry_Flux](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/938cc963c7754f56ccc30bb1e3b5764542d08d64/src/Enrgy_sub.m#L31) is used to calculate variables QET, QEB. However, they are unused in the model.

**Comment by yijianzeng** [comment]
> 1. The variables calculated in [these lines](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/938cc963c7754f56ccc30bb1e3b5764542d08d64/src/EnrgyPARM.m#L42-L45) are unused in the model.

Hi Sarah, this is ok, these lines are calculated, and can be put into output when requested. They are corresponding to Equation 3.9, and 3.10 in the STEMMUS technical note.

**Comment by yijianzeng** [comment]
> 2\. The function [Enrgy_Bndry_Flux](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/938cc963c7754f56ccc30bb1e3b5764542d08d64/src/Enrgy_sub.m#L31) is used to calculate variables QET, QEB. However, they are unused in the model.

The same, these are boundary fluxes calculated for any potential analysis, so could be deemed as model output and can be saved when requried.

**Comment by yijianzeng** [comment]
> 3\. `DDhDZ` is not defined as [InitialValues](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/938cc963c7754f56ccc30bb1e3b5764542d08d64/src/%2Binit/defineInitialValues.m#L119)!

hI Sarah, is this initialized [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/938cc963c7754f56ccc30bb1e3b5764542d08d64/src/STEMMUS_SCOPE.m#L463)
