### ISSUE TITLE
Adding a changelog file

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/STEMMUS_SCOPE#146]
Maintaining a file in which the changes for each version are documented is considered good practice, and quite standard in development of code and models.

For example, the changelog for SCOPE can be found [here](https://github.com/Christiaanvandertol/SCOPE/blob/master/docs/versions.rst).

STEMMUS_SCOPE is currently lacking such a file, and it would be best to add it as soon as possible.

**Comment by SarahAlidoost** [comment]
we can use something like https://github.com/rhysd/changelog-from-release to generate a changelog.
