### ISSUE TITLE
access to /projects/0/einf2480 on snellius?

### ISSUE THREAD

**Issue by AliciaPython** [EcoExtreML/STEMMUS_SCOPE#161]
Hi everyone, 

Does anyone know do I have access to /projects/0/einf2480 when I submit jobs? my sbatch script works with home and scratch-shared folder, but when I set it to /projects/0/einf2480, the sbatch script can not get result.
![image](https://github.com/EcoExtreML/STEMMUS_SCOPE/assets/90645468/13906a43-9e0f-4a0c-9ff9-d928041fa030)

Best, Qianqian Han

**Comment by AliciaPython** [comment]
I figured it out.

**Comment by SarahAlidoost** [comment]
@AliciaPython I see in your job script, the `cpus-per-task` is set to `128`. Does your code use all 128 CPUs to download data? if not, you can set it to the smallest amount which is 32. see https://servicedesk.surf.nl/wiki/display/WIKI/Snellius+usage+and+accounting and https://servicedesk.surf.nl/wiki/display/WIKI/Example+job+scripts

**Comment by AliciaPython** [comment]
Thanks for your advice Sarah. Surf people suggested me to use staging partition which is faster to download data, and also cheaper. Now I am using staging to download data.
