### ISSUE TITLE
Refactoring `Root_properties.m`

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/STEMMUS_SCOPE#163]
The file [Root_properties.m](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/Root_properties.m) has a few problems:

- Documentation is missing:
  - what does this function calculate?
  - what happens in the if-statements and loops?
- Three global variables are used. These should instead be passed to the function
- A lot of commented out code is in the file. If this code is unused it should be removed.

Additionally, it would be good to also rename the variables/structures according to the [style guide](http://cnl.sogang.ac.kr/cnlab/lectures/programming/matlab/Richard_Johnson-MatlabStyle2_book.pdf) where possible.

**Comment by Yunfei-Wang1993** [comment]
This equation was developed for the cropland and grassland in the GMD paper but it can't be used in forest sites. So, we commented it in the 170 sites running. Danyang will further develop it for forest sites.
