### ISSUE TITLE
Refactor and move all `cond*_` functions

### ISSUE THREAD

**Issue by SarahAlidoost** [EcoExtreML/STEMMUS_SCOPE#181]

**Comment by SarahAlidoost** [comment]
@yijianzeng For each function below, please add one line explanation and suggest a better name in this issue, thanks

- Condg_k_g
- CondL_h
- CondL_T
- CondL_Tdisp
- CondT_coeff
- CondV_DE
- CondV_DVg

**Comment by yijianzeng** [comment]
> 

- Condg_k_g ---->  gasConductivity
Ref: Scanlon, B. R. (2000), Soil gas movement in unsaturated systems, in Handbook of Soil Science, edited by M. E. Sumner, pp. A277– A319, CRC Press, Boca Raton, Fla.

Zeng, Y., Su, Z., Wan, L. and Wen, J.: Numerical analysis of air-water-heat flow in unsaturated soil: Is it necessary to consider airflow in land surface models?, J. Geophys. Res. Atmos., 116(D20), 20107, doi:10.1029/2011JD015835, 2011.

- CondL_h -------> hydraulicConductivity

- CondL_T -------> thermalHydraulicConductivity
Ref: Saito, H., J. Šimůnek, and B. P. Mohanty (2006), Numerical analysis of coupled water, vapor, and heat transport in the vadose zone, Vadose Zone J., 5(2), 784– 800.
Zeng, Y., Su, Z., Wan, L. and Wen, J.: Numerical analysis of air-water-heat flow in unsaturated soil: Is it necessary to consider airflow in land surface models?, J. Geophys. Res. Atmos., 116(D20), 20107, doi:10.1029/2011JD015835, 2011.

- CondL_Tdisp ---> transportCoefficientAbsorbedLiquidFlow
Ref: Groenevelt, P. H., and B. D. Kay (1974), On the interaction of water and heat transport in frozen and unfrozen soils: II. The liquid phase, Soil Sci. Soc. Am. Proc., 38, 400– 404,
Zeng, Y., Su, Z., Wan, L. and Wen, J.: Numerical analysis of air-water-heat flow in unsaturated soil: Is it necessary to consider airflow in land surface models?, J. Geophys. Res. Atmos., 116(D20), 20107, doi:10.1029/2011JD015835, 2011.

- CondT_coeff ---> thermalConductivityCapacity
Ref: Chung, S. O., and R. Horton (1987), Soil heat and water flow with a partial surface mulch, Water Resour. Res., 23(12), 2175– 2186,
Zeng, Y., Su, Z., Wan, L. and Wen, J.: Numerical analysis of air-water-heat flow in unsaturated soil: Is it necessary to consider airflow in land surface models?, J. Geophys. Res. Atmos., 116(D20), 20107, doi:10.1029/2011JD015835, 2011.

- CondV_DE -----> vaporDiffusionDispersionEnhancement
Zeng, Y., Su, Z., Wan, L. and Wen, J.: Numerical analysis of air-water-heat flow in unsaturated soil: Is it necessary to consider airflow in land surface models?, J. Geophys. Res. Atmos., 116(D20), 20107, doi:10.1029/2011JD015835, 2011.

Yu, L., Zeng, Y. and Su, Z.: STEMMUS-UEB v1.0.0: integrated modeling of snowpack and soil water and energy transfer with three complexity levels of soil physical processes, Geosci. Model Dev, 14, 7345–7376, doi:10.5194/gmd-14-7345-2021, 2021.

- CondV_DVg ----> gasLongitudinalDispersivity
Zeng, Y., Su, Z., Wan, L. and Wen, J.: Numerical analysis of air-water-heat flow in unsaturated soil: Is it necessary to consider airflow in land surface models?, J. Geophys. Res. Atmos., 116(D20), 20107, doi:10.1029/2011JD015835, 2011.

**Comment by SarahAlidoost** [comment]
@yijianzeng  While refactoring` Cond*_ ` functions, I found major issues, see below. Please help to address them: 
1. The *`_flm` variables are calculated [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L278-L335). But they are not used in STEMMUS_SCOPE.  Is this correct? Note that in refactoring work, [this code block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L278-L335) is deleted entirely.
2. in [CondL_h](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/CondL_h.m), Variables `Phi_s`, and `Lamda` are used for calculating other variables. However, they are empty vectors. Is this correct?
3. at [this code block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L153-L154), first, `Theta_II(ML, ND)` is calculated. Then it is used to calculate `Theta_LL(ML, ND)`. Later, again `Theta_LL(ML, ND) `is used to calculate `Theta_II(ML, ND)`, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L252). This is a case of "circular" calculation that might be an error. Can you check this?
4. In the comment above, you explained that "CondL_T script calculates the thermal-hydraulic conductivity, considering the temperature dependence of matric pressure.". However, [CondL_T](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/CondL_T.m) contains no useful code. Is this correct?
5. The variable `f0` is calculated in [CondV_DVg](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/CondV_DVg.m). However, this variable is not used by the rest of the code. Is this correct?
6. The variable `D_A` is calculated in [CondV_DE](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/CondV_DE.m). However, this variable is not used by the rest of the code. Is this correct?
7. can you suggest a better name and reference for [EfeCapCond](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/EfeCapCond.m)?

**Comment by SarahAlidoost** [comment]
@yijianzeng please have a look at the questions above.

**Comment by yijianzeng** [comment]
> 1. The *`_flm` variables are calculated [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L278-L335). But they are not used in STEMMUS_SCOPE.  Is this correct? Note that in refactoring work, [this code block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L278-L335) is deleted entirely.

Hi, Sarah, this film flow can improve the numerical convergence, since this is linked to soil water characteristic curve. Although it is not used in the current STEMMUS-SCOPE, this is an important part to account for freezing/thawing, which is to be activated later on.

**Comment by yijianzeng** [comment]
> 2\. in [CondL_h](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/CondL_h.m), Variables `Phi_s`, and `Lamda` are used for calculating other variables. However, they are empty vectors. Is this correct?

Hi Sarah, 'Phi_s' and 'Lamda' are parameters used by Clapp-Hornberger soil hydraulic model, see (Yu, Zeng, et al. JGR 2018). Although in STEMMUS-SCOPE, we used VG model, it is still making sense to keep Clapp-Hornberger model for future applications.

**Comment by yijianzeng** [comment]
> 3\. at [this code block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L153-L154), first, `Theta_II(ML, ND)` is calculated. Then it is used to calculate `Theta_LL(ML, ND)`. Later, again `Theta_LL(ML, ND) `is used to calculate `Theta_II(ML, ND)`, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L252). This is a case of "circular" calculation that might be an error. Can you check this?

Hi Sarah, 'Theta_II' is soil ice content, and 'Theta_LL' is liquid water content, 'Theta_UU' is the total water content before soil freezing. The 'Theta_UU' is set as saturation. This is also linked to (Yu, Zeng, et al. JGR 2018).

**Comment by yijianzeng** [comment]
> 4\. In the comment above, you explained that "CondL_T script calculates the thermal-hydraulic conductivity, considering the temperature dependence of matric pressure.". However, [CondL_T](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/CondL_T.m) contains no useful code. Is this correct?

It is indeed currently not used (e.g., mute the temperature dependence), but we should keep it for future extensions.

**Comment by yijianzeng** [comment]
> 5\. The variable `f0` is calculated in [CondV_DVg](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/CondV_DVg.m). However, this variable is not used by the rest of the code. Is this correct?

'f0' is the Tortuosity factor, it is used in 'CondV_E' see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondV_DE.m#L20). It would make sense to refactor it into a function.

**Comment by yijianzeng** [comment]
> 6\. can you suggest a better name and reference for [EfeCapCond](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/EfeCapCond.m)?

This is used to calculate  Heat Capacity and Thermal Conductivity. Perhaps renamed as 'SoilThermalProperites'.

**Comment by yijianzeng** [comment]
> 7\. There are two equations used to calculate `DTheta_UUh`. Those two equations are equal except that `Theta_s(J) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L139-L143)  whereas  `Theta_m(ML) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L56-L57). The same issue happened for variable `DTheta_LLh`, `Theta_s(J) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L191-L192) whereas `Theta_m(ML) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L91-L92C33) . Are those equations using `Theta_s` and `Theta_m` correct?

Hi Sarah, this is used by Lianyu to account for extremely dry condition, it is ok to keep them.

**Comment by SarahAlidoost** [comment]
> > 3. at [this code block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L153-L154), first, `Theta_II(ML, ND)` is calculated. Then it is used to calculate `Theta_LL(ML, ND)`. Later, again `Theta_LL(ML, ND) `is used to calculate `Theta_II(ML, ND)`, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L252). This is a case of "circular" calculation that might be an error. Can you check this?
> 
> Hi Sarah, 'Theta_II' is soil ice content, and 'Theta_LL' is liquid water content, 'Theta_UU' is the total water content before soil freezing. The 'Theta_UU' is set as saturation. This is also linked to (Yu, Zeng, et al. JGR 2018).

Hi Yijian, the issue here is the **circular calculation**. Do you mean this procedure is correct?

**Comment by SarahAlidoost** [comment]
> > 7. There are two equations used to calculate `DTheta_UUh`. Those two equations are equal except that `Theta_s(J) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L139-L143)  whereas  `Theta_m(ML) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L56-L57). The same issue happened for variable `DTheta_LLh`, `Theta_s(J) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L191-L192) whereas `Theta_m(ML) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L91-L92C33) . Are those equations using `Theta_s` and `Theta_m` correct?
> 
> Hi Sarah, this is used by Lianyu to account for extremely dry condition, it is ok to keep them.

The issue here is that those equations are exactly the same except for using `Theta_s` or `Theta_m` . Do you mean those equations are correct?

**Comment by yijianzeng** [comment]
> > > 3. at [this code block](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L153-L154), first, `Theta_II(ML, ND)` is calculated. Then it is used to calculate `Theta_LL(ML, ND)`. Later, again `Theta_LL(ML, ND) `is used to calculate `Theta_II(ML, ND)`, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L252). This is a case of "circular" calculation that might be an error. Can you check this?
> > 
> > 
> > Hi Sarah, 'Theta_II' is soil ice content, and 'Theta_LL' is liquid water content, 'Theta_UU' is the total water content before soil freezing. The 'Theta_UU' is set as saturation. This is also linked to (Yu, Zeng, et al. JGR 2018).
> 
> Hi Yijian, the issue here is the **circular calculation**. Do you mean this procedure is correct?

Hi Sarah, this procedure is correct in my check of this code block. The main confusion could come from many conditional statements. But the physics it represents reads fine to me.

**Comment by yijianzeng** [comment]
> > > 7. There are two equations used to calculate `DTheta_UUh`. Those two equations are equal except that `Theta_s(J) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L139-L143)  whereas  `Theta_m(ML) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L56-L57). The same issue happened for variable `DTheta_LLh`, `Theta_s(J) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L191-L192) whereas `Theta_m(ML) - Theta_r(J)` is used [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/0e0af05f00e9e73bc0b367f83056c079353dad89/src/CondL_h.m#L91-L92C33) . Are those equations using `Theta_s` and `Theta_m` correct?
> > 
> > 
> > Hi Sarah, this is used by Lianyu to account for extremely dry condition, it is ok to keep them.
> 
> The issue here is that those equations are exactly the same except for using `Theta_s` or `Theta_m` . Do you mean those equations are correct?

Yes Sarah, these equations are physically meaningful, it is used to account for extremely dry condition, and expect to improve numerical convergency.
