### ISSUE TITLE
Variables from STEMMUS_MODFLOW that needs to be included in STEMMUS_SCOPE for BMI purposes

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE#212]
Hi @yijianzeng and @Lianyu-Yu 

Looking at Lianyu code (branch[ "STEMMUS_MODFLOW_v1.0.0.")](https://github.com/EcoExtreML/STEMMUS_SCOPE/tree/STEMMUS_MODFLOW_v1.0.0), in the main script file ["MainLoop11.m", lines 85->87](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/083256e5540006841fc7bfe8ab223ac22ddc17be/src/MainLoop11.m#L85), there are the "hBOT" and "IBOT" variables. Those variables are already calculated in a separate function ["TIME_INTERPOLATION.m"](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/STEMMUS_MODFLOW_v1.0.0/src/TIME_INTERPOLATION.m), then they are passed to the main script "[MainLoop11.m](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/083256e5540006841fc7bfe8ab223ac22ddc17be/src/MainLoop11.m#L85)" and in the boundary condition calculations at the [h_BC.m](https://github.com/MostafaGomaa93/STEMMUS_MODFLOW/blob/ba12508210d191510d3125516b627e5f77bf8962/h_BC.m#L22C1-L26C45) file. 

However, those variables are not in STEMMUS_SCOPE source code. As I understand, we need to include these variables in the source code to let STEMMUS receive info from MODFLOW, right? Could you please explain what do "hBOT" and "IBOT"  mean?

**Comment by MostafaGomaa93** [comment]
[Lianyu-Yu](https://github.com/Lianyu-Yu)
Could you please also explain the meaning of all variables of the ["TIME_INTERPOLATION.m"](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/STEMMUS_MODFLOW_v1.0.0/src/TIME_INTERPOLATION.m)
function

T1,T0,IP,BOT,HPILLAR1N,HPILLAR0,T,DELT,X,NUMNP,Q3DF,ADAPTF

**Comment by MostafaGomaa93** [comment]
Could you aslo please explain what is the functualility of the [Diff_moisture_heat.m](https://github.com/MostafaGomaa93/STEMMUS_MODFLOW/blob/ba12508210d191510d3125516b627e5f77bf8962/Diff_Moisture_Heat.m#L238) file?

example, what is the use of hBOT in this [line](https://github.com/MostafaGomaa93/STEMMUS_MODFLOW/blob/ba12508210d191510d3125516b627e5f77bf8962/Diff_Moisture_Heat.m#L238)?

**Comment by Lianyu-Yu** [comment]
> Hi @yijianzeng and @Lianyu-Yu
> 
> Looking at Lianyu code (branch[ "STEMMUS_MODFLOW_v1.0.0.")](https://github.com/EcoExtreML/STEMMUS_SCOPE/tree/STEMMUS_MODFLOW_v1.0.0), in the main script file ["MainLoop11.m", lines 85->87](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/083256e5540006841fc7bfe8ab223ac22ddc17be/src/MainLoop11.m#L85), there are the "hBOT" and "IBOT" variables. Those variables are already calculated in a separate function ["TIME_INTERPOLATION.m"](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/STEMMUS_MODFLOW_v1.0.0/src/TIME_INTERPOLATION.m), then they are passed to the main script "[MainLoop11.m](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/083256e5540006841fc7bfe8ab223ac22ddc17be/src/MainLoop11.m#L85)" and in the boundary condition calculations at the [h_BC.m](https://github.com/MostafaGomaa93/STEMMUS_MODFLOW/blob/ba12508210d191510d3125516b627e5f77bf8962/h_BC.m#L22C1-L26C45) file.
> 
> However, those variables are not in STEMMUS_SCOPE source code. As I understand, we need to include these variables in the source code to let STEMMUS receive info from MODFLOW, right? Could you please explain what do "hBOT" and "IBOT" mean?

"hBOT" is the water head at the bottom soil layer; "IBOT" is the layer index where the current "bottom“ is. 
please see line 26 of the hBC.m file for how "hBOT" and "IBOT" are used.

**Comment by MostafaGomaa93** [comment]
Hi @Lianyu-Yu 

Could you please fill in the table with the meaning of the variables of the `HYDRUS1RECHARGE`

|  | Variable in [`MainLoop00.m`](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/083256e5540006841fc7bfe8ab223ac22ddc17be/src/MainLoop11.m#L274C1-L275C100) | Variable in [`HYDRUS1RECHARGE`](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/083256e5540006841fc7bfe8ab223ac22ddc17be/src/HYDRUS1RECHARGE.m#L1C1-L1C151) | Description |
|---|---|---|---|
| Ouput | dMOD | - | |
| Ouput | QQS | - | |
| Ouput | DW | - | |
| Ouput | RRrN | RrNGG | |
| Ouput | RrO | RrOGG | |
| Ouput | ZTB1 | ZTB1G | |
| Input | T1 | TEND1/86400 | |
| Input | T0 | TTIME | |
| Input | ITERQ3D | ITERQ3D | |
| Input | IP | IP0STm | |
| Input | IGRID | IGRID | |
| Input | Q3DF | Q3DF | |
| Input | THETA0 | THETA0 | |
| Input | ICTRL0 | ICTRL0 | |
| Input | THN | STheta_LL | |
| Input | T | TIME/86400 | |
| Input | QS | QS | |
| Input | DT | Delt_t/86400 | |
| Input | DELT | TTEND | |
| Input | ZTB0 | ZTB0G | |
| Input | HNEW | Shh | |
| Input | KPILLAR | KPILLAR | |
| Input | BOT | BOTm | |
| Input | RrN | RrNG | |
| Input | SY | SYSTG | |
| Input | SS | SSSTG | |
| Input | X | XElemnt | |
| Input | KTN | KTN | |

**Comment by MostafaGomaa93** [comment]
Hi @Lianyu-Yu

Could you please explain the difference between the outputs of the functions `FINDTABLE` and `TIME_INTERPLATION`? I am still confused about the difference between the two functions

| Function | Varaiable | Meaning |
 |---|---|---|
| TIME_INTERPOALTION | hBOT | head of the bottom layer where below that layer is the groundwater zone |
| TIME_INTERPOALTION | IBOT | index of the bottom layer that includes the groundwater head |
| FINDTABLE | ZTB | ?? |
| FINDTABLE | ICTRL | ?? |

**Comment by Lianyu-Yu** [comment]
Hi @MostafaGomaa93 
The explanation of "HYDRUS1RECHARGE.m" corresponds to the Appendix A in the file: https://doi.org/10.5194/gmd-2022-221, or the methodology part in this file: https://doi.org/10.5194/hess-23-637-2019.
Hope it is helpful to you.
