### ISSUE TITLE
How to set boundary conditions? Only from the source code? 

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE#213]
Hi @SarahAlidoost, @BSchilperoort and @yijianzeng 

Is the only way to set the boundary conditions (e.g. NBChB = 1 or 2 or 3) through changing the value [inside the source code](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/be6a9a724696106434d571a0f22920948a245f21/src/%2Binit/setBoundaryCondition.m#L65C1-L68C61)? or that could be done from outside (e.g. from a text file).

If I talk about STEMMUS_SCOPE_MODFLOW -> NBChB must be 1 always ( I see that default value is 3[ in this line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/be6a9a724696106434d571a0f22920948a245f21/src/%2Binit/setBoundaryCondition.m#L71)).

 Also, if there is groundwater temperature data available -> [NBCTB will be also = 1](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/be6a9a724696106434d571a0f22920948a245f21/src/%2Binit/setBoundaryCondition.m#L83C1-L87C19)

**Comment by SarahAlidoost** [comment]
> Is the only way to set the boundary conditions (e.g. NBChB = 1 or 2 or 3) through changing the value [inside the source code](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/be6a9a724696106434d571a0f22920948a245f21/src/%2Binit/setBoundaryCondition.m#L65C1-L68C61)? or that could be done from outside (e.g. from a text file).

Currently no. The variable `NBChB` is set only in one script `setBoundaryCondition.m`. If it is defined in a file such as the [config file](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/config_file_template.txt), it can be set from outside. In your case, if `NBChB` is always 1, then it can be set internally. There is also a file [getModelSettings.m.](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/%2Bio/getModelSettings.m) that contains some settings. It would be nice if eventually the content of this file is moved to the config file. But please note that some of those settings have not been tested, see #196

**Comment by MostafaGomaa93** [comment]
I would agree with @SarahAlidoost to move some of the content of both the setBoundaryCondtion and getModelSettings to the config file. It will be easier for the users later to change the settings based on their applications. That will also be helpful to generate a new exe with these modifications and be latter used with the BMI. what do you think @yijianzeng?

**Comment by Lianyu-Yu** [comment]
For STEMMUS-MODFLOW, all the STEMMUS settings are in the file `STEMMUS_config.m`, which is the combination of the original files 'Constants.m' and 'StartInit.m'.
