### ISSUE TITLE
Potential issue in the RWU calculations and a proposed enhancement

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE#231]
Calculations of the root water uptake (`RWU`) in the `ebal` function ([line 545](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/460e8ba060732820f110587fb74bbec59b9be795/src/ebal.m#L545)) are based on the difference between the soil water potential `PSIs` and the leave water potential `PSI`. The `PSIs` (calculated in [line 177](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/460e8ba060732820f110587fb74bbec59b9be795/src/ebal.m#L177)) is from the `calc_rsoil`. Going inside the `calc_rsoil` function [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/460e8ba060732820f110587fb74bbec59b9be795/src/calc_rsoil.m#L9), the `PSIs` equation seems a bit strange to me. 

- First: why do we need to re-calculate the soil water potential, while we have it already from STEMMUS (Soilvariable.hh). The reason I guess is that the `ebal` function is a SCOPE function, where there is no soil model and the PSIs equation is a simple way to get the soil matric potential using only the Van-Genechten equation. But I think since we work with STEMMUS_SCOPE, we don't need to re-calculate the soil water potential and it is better to replace the `PSIs` with `Soilvariable.hh`
- Second, there is a big difference between the values of the `PSIs` and `Soilvariable.hh`. The difference is almost two orders of magnitude. `PSIs` is in range (-30 to -2) cm/sec, while the `Soilvariable.hh` is in range (-1500 to -300). Consequently, there are almost two orders of magnitude difference between the RWU if it is calculated using `PSIs` and if it is calculated using `Soilvariable.hh`. 
- Third, the `PSIs` calculations in [line 9](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/460e8ba060732820f110587fb74bbec59b9be795/src/calc_rsoil.m#L9) has a multiplication of 100 in the term (`(Alpha * 100)`. I wonder if that multiplication by the 100 causes that difference between the `PSIs` and `Soilvariable.hh`, if so, maybe I am missing something here, what is the use of this 100 multiplication? Probably @Yunfei-Wang1993 Could clarify this

**Comment by Yunfei-Wang1993** [comment]
Hi, Mostafa, the calculation of soil water potential is based on Bayat's work published in RSE. The multiplication by 100 is a unit conversion from 'cm' to 'm'. The unit is 'cm' in STEMMUS and it usually uses 'm' in the SPAC equation. The Soilvariable.hh means the water potential at the soil nodes rather than the average soil water potential of each soil layer. So, I recalculate the soil water potential of each soil layer.

**Comment by MostafaGomaa93** [comment]
Hi @Yunfei-Wang1993 

Okay, I indeed suspect that the 100 is a unit conversion from cm to m but why is that? what is the SPAC equation?

I noticed you later had to convert it back to "cm" in the equation
`Srt1 = RWU * 100 ./ ModelSettings.DeltZ'` [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/460e8ba060732820f110587fb74bbec59b9be795/src/%2Bsoilmoisture/calculateEvapotranspiration.m#L23). 

But I still have some more questions:
- 1. If you just want the average soil water potential of each soil layer, Why you didn't get it from the average of the  `Soilvariable.hh` of the two nodes of each soil layer? something like 
`hh_avg = [ Soilvariable.hh(i) + Soilvariable.hh(i+1) ] / 2`
- 2. what is the purpose of the `ModelSettings.DeltZ` division in the equation above?

I am asking because when we add the groundwater coupling, for the saturated soil layers, the `Soilvariable.hh` converts to a +ve value, but I am not sure if the `PSIs` will have +ve values for saturated layers. Moreover, the `Soilvariable.hh` in my opinion is more accurate than the `PSIs` because the `Soilvariable.hh` is calculated from the main equations of the code (i.e. Milly equation)

**Comment by MostafaGomaa93** [comment]
I discussed with @yijianzeng and @Yunfei-Wang1993 and made changes in the `PSIs` to correct the matric potential calculations if groundwater coupling is activated. The changes are implemented in the SSM_v.0.3.2 branch [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/a269115fa2783bb3f102f64b79ab248862a16c33/src/calc_rsoil.m#L12-L18)
