### ISSUE TITLE
Unused variables and equations in `groundwater` module

### ISSUE THREAD

**Issue by SarahAlidoost** [EcoExtreML/STEMMUS_SCOPE#240]
@BSchilperoort and @MostafaGomaa93 There are some variables defined in scripts of  `+groundwater` module that are not used by the rest of the model.

**Comment by MostafaGomaa93** [comment]
Hi @SarahAlidoost. These unused variables are already part of the coupling methodology that we follow (https://doi.org/10.5194/hess-23-637-2019). However, as indicated in this [line](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/%2Bgroundwater/calculateGroundwaterRecharge.m#L96), the effect of these variables are minor, but I kept them for further testing in the future. 

So, I would prefer we don't remove them. Maybe we can comment them in the meantime
