### ISSUE TITLE
Change thickness of soil layers from outside the code

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE#241]
The thickness of the soil layers is calculated in the [`Dtrmn_Z`](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/Dtrmn_Z.m) function. The calculations are fixed (first 1-3 layers with thickness = 1 cm, next 4-14 layers with thickness = 2 cm, ...... and from layer 42-end, thickness is 20 cm).

I was thinking of an option to import the layers' thickness from an external input file (e.g. txt file) instead of hardcoding them in the code. This will allow for some flexibility, which is highly needed when we have a deeper soil profile (e.g. 10 or 20 m), so to increase a bit the layers' thickness (especially for deeper layers) and consequently minimize the running time. 

@yijianzeng, what do you think? If agreed, I can discuss further with @SarahAlidoost about the best input option to use (txt, netcdf, whatever) and then we can modify the [`Dtrmn_Z`](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/Dtrmn_Z.m) function. We can keep the `Dtrmn_Z` function as default and use the external input as an option if the user needs

**Comment by Crystal-szj** [comment]
Hi @MostafaGomaa93, Thanks for opening this issue. 
@yijianzeng @SarahAlidoost The value of [Tot_Depth](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/2f9f468186c5a115e272f0de10344e23104e9b2e/src/%2Bio/getModelSettings.m#L54) is involved in the calculation of soil layers thickness, and it is currently hardcoded in STEMMUS-SCOPE with a value of 500 cm. This fixed value may not be suitable for all sites. I think we should improve it as well

**Comment by SarahAlidoost** [comment]
lets create a csv file to store the soil layer information and add it to the repository under a new folder"data" (perhaps this can be moved to a zenodo entry).

**Comment by yijianzeng** [comment]
@MostafaGomaa93 @SarahAlidoost @Crystal-szj This sounds tangible to me. One would like to have a more 'generic'/'flexible' Dtrmn_Z, so the layer thickness as well as the total depth can be defined by the end-user via configure file, or a csv file. 

In my opinion, csv file can do, but then it is then again creating additional file, on top of the config file, so question here:
Shall we include all info into one config file?

One principle should be followed. The top layer should be sufficiently fine (e.g., 1mm-5mm, for the top 1cm or so), and then increase the thickness in an exponential manner, which is usually an optimal combination between the number of layers and the need for an accurate numerical solution of STEMMUS.

**Comment by SarahAlidoost** [comment]
> @MostafaGomaa93 @SarahAlidoost @Crystal-szj This sounds tangible to me. One would like to have a more 'generic'/'flexible' Dtrmn_Z, so the layer thickness as well as the total depth can be defined by the end-user via configure file, or a csv file.
> 
> In my opinion, csv file can do, but then it is then again creating additional file, on top of the config file, so question here: Shall we include all info into one config file?

Right, but the current configuration file is a `txt` file, which does not have the flexibility needed to add structured data. The path to the CSV file can be included in the configuration file. Switching to other formats for example YAML format would allow for better support of these types of data, see [my previous comment about adding variables to the config file. ](https://github.com/EcoExtreML/STEMMUS_SCOPE/issues/237#issuecomment-2203353258)

**Comment by MostafaGomaa93** [comment]
A new [branch](https://github.com/EcoExtreML/STEMMUS_SCOPE/tree/add_csv_for_soil_layers_settings) with a new [pull request](https://github.com/EcoExtreML/STEMMUS_SCOPE/pull/243) is pushed to 
- add a new function that reads a new csv for importing soil layers settings
- add a new function to check the model run per time step
