### ISSUE TITLE
Run `getModelSettings` twice to initialize model settings

### ISSUE THREAD

**Issue by Crystal-szj** [EcoExtreML/STEMMUS_SCOPE#246]
Hi @SarahAlidoost,

I found that the `getModelSettings.m` file runs twice in  [Line 48](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/STEMMUS_SCOPE.m#L48-L49) of the `STEMMUS_SCOPE.m` https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/STEMMUS_SCOPE.m#L48-L49
and in function [`init.defineInitialValues`](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Binit/defineInitialValues.m#L6-L7) in line 58 of `STEMMUS-SCOPE.m` 
 https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8cce9c6cbf277c3ea3d0757754aaa00389643629/src/%2Binit/defineInitialValues.m#L6-L7

I think they are both used to initialize model settings. Is there any consideration for further model development? Otherwise, If they are run twice without any difference, I can revise it.

**Comment by SarahAlidoost** [comment]
@Crystal-szj It is not only those two scripts. [A search on the repository shows](https://github.com/search?q=repo%3AEcoExtreML%2FSTEMMUS_SCOPE+path%3A%2F%5Esrc%5C%2F%2F+ModelSettings+%3D+io.getModelSettings%28%29&type=code) that `ModelSettings = io.getModelSettings()` is used in several scripts requiring model settings. This approach avoids using global variables and adding multiple input arguments to functions. Whenever your code needs the model settings, you simply call `io.getModelSettings()`, ensuring a consistent reference to a single set of settings. Therefore, no need to revise something.
