### ISSUE TITLE
Add groundwater recharge temperature to the BMI variables

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE#256]
Add [groundwater recharge temperature](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/6689fe469cc946dbc485388a7bce5989b6d13477/src/%2Bgroundwater/calculateGroundwaterRecharge.m#L101C1-L103C48) to the BMI variables

**Comment by SarahAlidoost** [comment]
As suggested in the pull request review in #257, instead, the recharge index is exposed to BMI.
