### ISSUE TITLE
soil temperature can become imaginary number

### ISSUE THREAD

**Issue by MostafaGomaa93** [EcoExtreML/STEMMUS_SCOPE#270]
Hi @BSchilperoort,
I received this below error which I have no idea how to solve. I try different things but doesn't work. Any suggestion how to solve

![error](https://github.com/user-attachments/assets/914239b0-cd60-4b70-bf59-f412854b4307)

**Comment by MostafaGomaa93** [comment]
Okay, I think I managed to solve it. 

The error message is not really relevant to the solution (at least to me). This error happens when I try to change/update the soil parameters values in the soil_parameters.mat file (so not to use the one generated by PyStemmusScope). It is also not really related to the `soil_temperature` variable because when I switch off the line that retrieves the `soil_tempearture` in BMI, I still get the same error. 

The solution was to use the same Python package (**hdf5storage**) if the user wanted to change/update the soil_parameters.mat file. So, initially, I was using the **h5py** Python package to get a new mat file for soil parameters. When I generate the new mat file using **hdf5storage** instead of **h5py**, the error is gone. I really don't know why it works like that and what is the difference because both packages should do the same thing, but there might be changes in the format of the values at the end which led to the error

**Comment by BSchilperoort** [comment]
> I really don't know why it works like that and what is the difference because both packages should do the same thing

.mat files do use hdf5 to store data but MATLAB is very picky about how, and about meta-data. This is why [v7.3 mat file support is explicitly mentioned in hdf5storage](https://pythonhosted.org/hdf5storage/information.html#matlab-mat-v7-3-file-support). It still uses h5py to read the hdf5 data.
