### ISSUE TITLE
Executable file incompatible with Windows

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/STEMMUS_SCOPE#93]
After installing Matlab runtime, I get the following error trying to run the executable file in Windows:
```
The specified executable is not a valid application for this OS platform 
```

We should figure out what is required to generate an executable file that is compatible with Windows, or how to properly run the executable file on Windows.

**Comment by SarahAlidoost** [comment]
The executable file works on the operating system on which the file is created. This should be explained in the documentation.
