### ISSUE TITLE
Refactor `Constants.m`

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/STEMMUS_SCOPE#95]
In STEMMUS_SCOPE.m, the script `Constants` is called. Despite its name, it seems to be used for all of the following:
- Configuring model settings
- Initializing variables
- Defining constants

For model maintainability we want to remove all use of globals and running scripts. `Contants` can be a function that generates a struct with constants, but these should be only physical or model constants _that never change_.

For example:
```matlab
>> Constants.g % gravitational accelaration
Costants.g = 9.81
```

<hr>

To do:

- [ ] Assess which parts of the script belong where (model settings/intialization/constants)
- [ ] Move model settings to a fitting function
- [ ] Move initialization to the correct function(s)
- [ ] Refactor constants so it generates a struct containing only constants
- [ ] Refactor StartInit and other scripts that use those variables from `Constants.m`

**Comment by SarahAlidoost** [comment]
Hi @yijianzeng, while I was refactoring the Constants.m, I found some issues in the code, see below. 
1- variable `R_depth` is set to `300` in Constants.m, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8454ce41c07b72f8bd07687b2ea805fbdd2df43b/src/Constants.m#L31). But it is reset to 350 in  Max_Rootdepth, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8454ce41c07b72f8bd07687b2ea805fbdd2df43b/src/Max_Rootdepth.m#L15). Which one is correct?
2. variable `RHO_bulk` defined in `Constants.m`, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8454ce41c07b72f8bd07687b2ea805fbdd2df43b/src/Constants.m#L407) and it is used in `CondL_Tdisp`, and `CondT_coeff`. But a similar variable `RHo_bulk` is defined in `calculateInitialThermal.m`, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8454ce41c07b72f8bd07687b2ea805fbdd2df43b/src/%2Binit/calculateInitialThermal.m#L59). Is this correct?
3. variable `ML` is used as an indexer in loops in `Constants.m`, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8454ce41c07b72f8bd07687b2ea805fbdd2df43b/src/Constants.m#L34-L40). But it is also used to create empty matrixes, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8454ce41c07b72f8bd07687b2ea805fbdd2df43b/src/Constants.m#L349-L369). Is this correct?

**Comment by EntingTang** [comment]
Hi @SarahAlidoost . I think I can answer the question 1 of `R_depth`. Only the `R_depth` in Max_Rootdepth is read and used for further calculation. Please correct me if I am wrong @Yunfei-Wang1993 @yijianzeng

**Comment by Crystal-szj** [comment]
Hi, @SarahAlidoost I agree with Enting about the value of `R_depth`.  In `Constants.m`, the `R_depth` is defined initially, but the value we used in the calculation should be the value in `Max_Rootdepth`.

About question 3, since the value of `Eqlspace` is 0, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8454ce41c07b72f8bd07687b2ea805fbdd2df43b/src/Constants.m#L32), thus the value of `ML` is calculated by `Dtrmn_Z.m`. The value of `ML` means the number of soil layers.

**Comment by SarahAlidoost** [comment]
> About question 3, since the value of `Eqlspace` is 0, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8454ce41c07b72f8bd07687b2ea805fbdd2df43b/src/Constants.m#L32), thus the value of `ML` is calculated by `Dtrmn_Z.m`. The value of `ML` means the number of soil layers.

Thanks. I don't see where in `Dtrmn_Z.m`, the variable `ML` is calculated. Can you mention the line number? 
In the `Dtrmn_Z.m`, the variable `ML`  is used as an index for looping over some sets of numbers e.g. for `ML = 1:42`. Therefore, the value of ML is changing between `1` and `42`. On the other hand, `ML` is also used to create empty matrixes, see [here](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/8454ce41c07b72f8bd07687b2ea805fbdd2df43b/src/Constants.m#L349-L369). This is not correct.
