### ISSUE TITLE
Refactor `SOIL1` and `SOIL2`

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/STEMMUS_SCOPE#96]
In the main `STEMMUS_SCOPE.m` script, on the following line `SOIL1` is run:
https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/d2fe0a671ab26430f086e1c8ee8272f4db6fa060/src/STEMMUS_SCOPE.m#L639

This is a relatively small script, which can probably be easily turned into a function. Also, the function description states that "This subroutine is called after one time step to update the wetting history". Wouldn't it make more sense to name this function `update_wetting_history`?

To refactor this function, the following has to be done:

- [ ] Determine the inputs and outputs of the function
- [ ] Rewrite it so it takes arguments as inputs, and returns the changed variables as output
- [ ] Change the main script to be compatible with these changes
- [ ] Commit the changes to a new branch and create a pull request

**Comment by SarahAlidoost** [comment]
@yijianzeng The name of `SOIL2` function can be changed to something more descriptive. Any suggestion for a better name for [`SOIL2` function](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/SOIL2.m)?

**Comment by yijianzeng** [comment]
> @EcoExtreML/developers The name of `SOIL2` function can be changed to something more descriptive. Any suggestion for a better name for [`SOIL2` function](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/SOIL2.m)?

hI Sarah, i am sorry that i was continuously on travel. Last week in Naples, and i am now at Bruges for an ESA EO Science Strategy Study Workshop. Yes, we can renaming "SOIL2.m" as "updating_ThetaLL.m". If this 'ThetaLL' is not ideal, we can just say 'Updating_SoilWaterContent.m'

**Comment by yijianzeng** [comment]
> > @EcoExtreML/developers The name of `SOIL2` function can be changed to something more descriptive. Any suggestion for a better name for [`SOIL2` function](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/src/SOIL2.m)?
> 
> @yijianzeng please help answer this question. thanks

I am sorry for the late reply.
