### ISSUE TITLE
Refactor `Air_sub`, move all `Air_` functions 

### ISSUE THREAD

**Issue by BSchilperoort** [EcoExtreML/STEMMUS_SCOPE#99]
In STEMMUS_SCOPE.m, all `Air_` functions are called using the script `Air_sub`:

https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/d2fe0a671ab26430f086e1c8ee8272f4db6fa060/src/STEMMUS_SCOPE.m#L747

However, for model maintainability we want to remove all use of globals and running scripts.

Additionally, as all `Air_` functions seem to tackle one specific part of the model, these should be moved to a separate Matlab package with a appropriate name.

<hr>

To do:
- [ ] Move all `Air_` files to their own package, with an appropriate name
- [ ] Convert `Air_sub` into a function. Use structures to reduce the amount of input and output variables.
- [ ] Add documentation to all functions
- [ ] Make the required changes in the main file.
- [ ] Create a pull request for the changes

**Comment by SarahAlidoost** [comment]
@yijianzeng For each function below, please add one line explanation and suggest a better name in this issue, thanks

- Air_sub
- AirPARM
- Air_MAT
- Air_EQ
- Air_BC
- Air_Solve

**Comment by yijianzeng** [comment]
> @yijianzeng For each function below, please add one line explanation and suggest a better name in this issue, thanks
> 
> * Air_sub

This function is to solve the dry air equation with the Thomas algorithm ('Air_solve') to update the soil air pressure ('P_gg'), the finite difference time-stepping scheme is exampled as for the soil moisture equation, which derived in 'STEMMUS Technical Notes' section 4, Equation 4.32.

**Comment by yijianzeng** [comment]
> * AirPARM

This function calculates all the parameters related to dry air equation (e.g., Equation 3.59-3.64, STEMMUS Technical Notes, page 27-28).

**Comment by yijianzeng** [comment]
> * Air_MAT

This function calculates all the parameters related to matric coefficients (e.g., c1-c7) as in Equation 4.32 (STEMMUS Technical Notes, page 44, which is an example for soil moisture equation), but for dry air equation.

**Comment by yijianzeng** [comment]
> * Air_EQ

This function calculates all the parameters related to matric coefficients (e.g., c1-c7) as in Equation 4.32 (STEMMUS Technical Notes, page 44), for dry air equation.

**Comment by yijianzeng** [comment]
> * Air_BC

This function determines the boundary condition for solving the dry air equation.

**Comment by yijianzeng** [comment]
> * Air_Solve

This function uses Thomas algorithm to solve the tridiagonal matrix equations, which is in the form of Equation 4.25 (STEMMUS Technical Notes, page 41)
